feat: added the card component
pradipgharge/Linear-UI pull request #6
Opened 2022-02-16 20:04 UTC by pradipgharge

2022-02-16 20:21 UTC, sri-rishi requested changes

2022-02-16 20:21 UTC, sri-rishi commented on css/utilities.css
> +    color:rgb(107, 105, 105);
use color variable naming

2022-02-16 20:21 UTC, sri-rishi commented on pages/components/Cards/cards.css
> +    padding: 0.8rem 0.6rem;
use px for units less than 1rem

2022-02-16 20:53 UTC, manish-GH approved these changes
Add a cursor: pointer on hover for dismiss button and wishlist button. You could consider changing the on hover color for the blue button.

Everything else looks good, nice work

2022-02-17 05:13 UTC, sri-rishi approved these changes

2022-02-17 06:31 UTC, manish-GH approved these changes

2022-02-17 06:43 UTC, Anurag021 approved these changes
Code looks good to me.

2022-02-17 06:54 UTC, pradipgharge commented on pages/components/Cards/cards.css
> +    padding: 0.8rem 0.6rem;
Made the suggested changes

2022-02-17 06:55 UTC, merged